### ISSUE TITLE
Some out of date contact info and a new scraper needed

### ISSUE THREAD

**Issue by bahoo** [spacedogXYZ/us_governors_contact#1]
A friendly heads up, some of these seats have changed hands since the 2016 Election, and [the contact page itself on NGA.org](https://www.nga.org/cms/governors/addresses) has also gotten a recent revamping. I didn't have the appetite for learning the ropes with morph.io, but this gist should get you most of the way there: https://gist.github.com/bahoo/4bae8e2035ecfd971ec2504d29fdba0e

**Comment by jlev** [comment]
Thanks Jon (just seeing this now)!

Morph.io is kind of defunct, but it was a nice way to maintain scrapers without having to run them yourself to watch for changes. Your code is a lot easier to grok.
